apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    name: node
  labels:
    app: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
<<<<<<< HEAD
      - name: node
        image: node:2x
        imagePullPolicy: Never
=======
      - args:
        - bash
        - -c
        - npm install --prod && npm start
        image: node:_version_
        name: node
>>>>>>> 28fcb16d2eba2d65a6b9a38ec25e4463b257faaa
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
