apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
  name: kube-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
